export const itemsList = [
    { title: 'בגדים', year: 1994 },
    { title: 'חולצות', year: 1972 },
    { title: 'מכנסיים', year: 1974 },
    { title: 'גרביים', year: 2008 },
    { title: 'בגדים לשינה', year: 1957 },
    { title:  "מעיל", year: 1993 },
    { title: "ז'קט", year: 1994 },
    { title: 'מעיל גשם/ רוח', year: 2003 },
    { title: 'נעלי הליכה', year: 1966 },
    { title: 'נעלי בית', year: 1999 },
    { title: 'כפכפים', year: 2001 },
    { title: 'חגורות', year: 1980 },
    { title: 'עניבות', year: 1994 },
    { title: 'מגבות', year: 2010 },
    { title: 'משכורת', year: 2002 },
    { title: "פנס", year: 1975 },
    { title: 'בגד ים', year: 1990 },
    { title: 'מצפן', year: 1999 },
    { title: 'ארנק', year: 1954 },
    { title: 'שעון', year: 1977 },
    { title: 'פלאפון', year: 2002 },
    { title: 'ספר', year: 1995 },
    { title: 'תרופות', year: 1991 },
    { title: "טלויזיה", year: 1946 },
    { title: 'סוני פלייסטישן', year: 1997 },
    { title: 'מחשב נייד', year: 1995 },
    { title: 'מחבט טניס', year: 1994 },
    { title: "מוצ'ילה", year: 2001 },
    { title: 'שתייה', year: 1998 },
    { title: 'שכר דירה', year: 1968 },
    { title: 'שתייה', year: 1998 },
    { title: 'ציוד ספורט', year: 2014 },
    { title: 'משלוחים', year: 1942 },
    { title: 'כיבוד', year: 1931 },
    { title: 'דלק', year: 1960 },
    { title: 'צרכי משרד', year: 1999 },
    { title: 'ליסינג/השכרה', year: 2011 },
    { title: 'חומרה', year: 1936 },
    { title: 'תוכנה', year: 1981 },
    { title: 'הוצאות בנק', year: 1954 },
    { title: 'אגרות', year: 2002 },
    { title: 'קניות בחו"ל', year: 2006 },
    { title: 'רהיט', year: 1991 },
    { title: 'חומרי ביניין', year: 1985 },
    { title: 'ציוד מוזיקה', year: 2014 },
    { title: 'מנוי אינטרנט', year: 2000 },
    { title: 'שירותים מקצועיים', year: 2000 },
    { title: 'תשלום לקבלני משנה', year: 2006 },
    { title: 'פרסום וקידום מכירות', year: 1994 },
    { title: 'עמלות אשראי', year: 1979 },
    { title: 'פיצויים לעובדים', year: 1979 },
    { title: 'נסיעות', year: 1950 },
    { title: 'הלוואה', year: 1964 },
    { title: 'פיקדון', year: 1940 },
    { title: 'חשבון חשמל', year: 1988 },
    { title: 'ארנונה', year: 2006 },
    { title: 'תקציב', year: 1988 },
    { title: 'אוכל', year: 1957 },
    { title: 'הוצאות טלפון', year: 2012 },
    { title: 'אחזקה בעסק', year: 1980 },
    { title: 'יציאות חברים', year: 2008 },
    { title: 'ציוד לעסק', year: 1999 },
    { title: 'הוצאות דואר', year: 2012 },
    { title: 'לקרן השתלמות', year: 1997 },
    { title: 'שכירות/משרד', year: 1986 },
    { title: 'דומיינים', year: 2003 },
    { title: 'אחזקת רכב', year: 1984 },
    { title: 'טיפולי שיניים', year: 1957 },
    { title: 'ביטוח לאומי', year: 1981 },
    { title: 'עבודה זמנית', year: 1941 },
    { title: 'שכר לימוד', year: 1959 },
    { title: 'גז', year: 1958 },
    { title: 'חניות', year: 1983 },
    { title: 'עזרה מההורים', year: 1992 },
    { title: 'מתנות לאירועים', year: 1995 },
    { title: 'משיכת מזומן', year: 1931 },
    { title: 'אופטיקה', year: 2000 },
    { title: 'חשבון מיים', year: 2001 },
    { title: 'מיסי יישוב', year: 1971 },
    { title: 'וועד בית', year: 2007 },
    { title: 'מנויים', year: 1976 },
    { title: 'תרומות', year: 1962 },
    { title: 'קורסים', year: 1944 },
    { title: 'קניות לבית', year: 2004 },
    { title: 'מס הכנסה', year: 1984 },
    { title: 'שיפוצים', year: 1962 },
    { title: 'קולנוע', year: 2010 },
    { title: 'הלוואה לחבר', year: 2017 },
    { title: 'תיספורות', year: 1987 },
    { title: 'Dangal', year: 2016 },
    { title: 'The Sting', year: 1973 },
    { title: 'A Space Odyssey', year: 1968 },
    { title: "Singin' in the Rain", year: 1952 },
    { title: 'Toy Story', year: 1995 },
    { title: 'Bicycle Thieves', year: 1948 },
    { title: 'The Kid', year: 1921 },
    { title: 'Inglourious Basterds', year: 2009 },
    { title: 'Snatch', year: 2000 },
    { title: 'Idiots', year: 2009 },
    { title: 'Monty Python and the Holy Grail', year: 1975 },
  ];