export const itemsList = [
    { title: 'בגדים', year: 1994 },
    { title: 'חולצות', year: 1972 },
    { title: 'מכנסיים', year: 1974 },
    { title: 'גרביים', year: 2008 },
    { title: 'בגדים לשינה', year: 1957 },
    { title:  "מעיל", year: 1993 },
    { title: "ז'קט", year: 1994 },
    { title: 'מעיל גשם/ רוח', year: 2003 },
    { title: 'נעלי הליכה', year: 1966 },
    { title: 'נעלי בית', year: 1999 },
    { title: 'כפכפים', year: 2001 },
    { title: 'חגורות', year: 1980 },
    { title: 'עניבות', year: 1994 },
    { title: 'מגבות', year: 2010 },
    { title: 'משכורת', year: 2002 },
    { title: "פנס", year: 1975 },
    { title: 'בגד ים', year: 1990 },
    { title: 'מצפן', year: 1999 },
    { title: 'ארנק', year: 1954 },
    { title: 'שעון', year: 1977 },
    { title: 'פלאפון', year: 2002 },
    { title: 'ספר', year: 1995 },
    { title: 'תרופות', year: 1991 },
    { title: "טלויזיה", year: 1946 },
    { title: 'סוני פלייסטישן', year: 1997 },
    { title: 'מחשב נייד', year: 1995 },
    { title: 'מחבט טניס', year: 1994 },
    { title: "מוצ'ילה", year: 2001 },
    { title: 'שתייה', year: 1998 },
    { title: 'שכר דירה', year: 1968 },
    { title: 'שתייה', year: 1998 },
    { title: 'ציוד ספורט', year: 2014 },
    { title: 'משלוחים', year: 1942 },
    { title: 'כיבוד', year: 1931 },
    { title: 'דלק', year: 1960 },
    { title: 'צרכי משרד', year: 1999 },
    { title: 'ליסינג/השכרה', year: 2011 },
    { title: 'חומרה', year: 1936 },
    { title: 'תוכנה', year: 1981 },
    { title: 'הוצאות בנק', year: 1954 },
    { title: 'אגרות', year: 2002 },
    { title: 'קניות בחו"ל', year: 2006 },
    { title: 'רהיט', year: 1991 },
    { title: 'חומרי ביניין', year: 1985 },
    { title: 'ציוד מוזיקה' },
    { title: 'מנוי אינטרנט'},
    { title: 'שירותים מקצועיים'},
    { title: 'תשלום לקבלני משנה'},
    { title: 'פרסום וקידום מכירות'},
    { title: 'עמלות אשראי'},
    { title: 'פיצויים לעובדים'},
    { title: 'נסיעות'},
    { title: 'הלוואה'},
    { title: 'פיקדון'},
    { title: 'חשבון חשמל'},
    { title: 'ארנונה'},
    { title: 'תקציב'},
    { title: 'אוכל'},
    { title: 'הוצאות טלפון'},
    { title: 'אחזקה בעסק'},
    { title: 'יציאות חברים'},
    { title: 'ציוד לעסק'},
    { title: 'הוצאות דואר'},
    { title: 'לקרן השתלמות'},
    { title: 'שכירות/משרד'},
    { title: 'דומיינים'},
    { title: 'אחזקת רכב'},
    { title: 'טיפולי שיניים'},
    { title: 'ביטוח לאומי'},
    { title: 'עבודה זמנית'},
    { title: 'שכר לימוד'},
    { title: 'גז'},
    { title: 'חניות'},
    { title: 'עזרה מההורים'},
    { title: 'מתנות לאירועים'},
    { title: 'משיכת מזומן'},
    { title: 'אופטיקה'},
    { title: 'חשבון מיים'},
    { title: 'מיסי יישוב'},
    { title: 'וועד בית'},
    { title: 'מנויים'},
    { title: 'תרומות'},
    { title: 'קורסים'},
    { title: 'קניות לבית'},
    { title: 'מס הכנסה'},
    { title: 'שיפוצים'},
    { title: 'קולנוע'},
    { title: 'הלוואה לחבר' },
    { title: 'תיספורות'},
    
  ];